config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "admins/sessions", registrations: "admins/registrations" }
  root to: 'requests#is_user_login'
  resources :requests
  resources :searches
  resources :slas, only: [:new, :create, :destroy]
  resources :departments, only: [:new, :create]
  get 'settings', to: 'settings#show'
  get 'add_newuser', to: 'settings#add_newuser'
  
end

app/models/department.rb
class Department < ActiveRecord::Base
  has_many :users
  has_many :requests
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :user
  belongs_to :department
  belongs_to :sla
  
  validates :initiator,
            :comment, 
            :department_id, 
            :user_id, 
            :status, 
            :sla_id, presence: true

  before_create :set_deadline

  
  def self.find_requests(search)
    if search
      Request.where("comment LIKE ?", '%'+search+'%')
    else
      Request.all
    end
  end

  def check_deadline_status
    deadline <= DateTime.now && self.status == "В работе"
  end
  
  def set_deadline_if_it_after_or_before_work_day
    cur_year = DateTime.now.year
    cur_month = DateTime.now.month
    cur_day = DateTime.now.day
    start_work_day = DateTime.civil_from_format :local, cur_year, cur_month, cur_day, 9, 0, 0
    end_work_day = DateTime.civil_from_format :local, cur_year, cur_month, cur_day, 18, 0, 0
    if self.deadline.hour < 9
      self.deadline = DateTime.civil_from_format :local, deadline.year, deadline.month, deadline.day, 9,0,0
    elsif self.deadline.hour > 18
      new_day = deadline.day + 1.day
      self.deadline = DateTime.civil_from_format :local, deadline.year, deadline.month, new_day, 9,0,0 
    end

  end
  
  def set_deadline
    @sla_weight = Sla.find(self.sla_id).time_for_deadline
    self.deadline = DateTime.now.advance(hours: @sla_weight)
    set_deadline_if_it_after_or_before_work_day
  end

end

app/models/search.rb
class Search < ActiveRecord::Base
  
  def requests
    @requests ||= find_requests
  end

private
  
  def find_requests
    
    # Сначала присваиваем все записи
    requests = Request.order(:id)
    
    # Начинаем отбирать из всех те записи, которые попадают под условия
    requests = requests.where("comment LIKE ?", '%'+keywords+'%') if keywords.present?
    requests = requests.where(id: request_id) if request_id.present?
    requests = requests.where("deadline > ?", deadline) if deadline.present?
    requests = requests.where(sla_number: sla) if sla.present?
    requests = requests.where(responsible: responsible) if responsible.present?
    requests = requests.where(division: division) if division.present?
    return requests
  end

end

app/models/sla.rb
class Sla < ActiveRecord::Base
  has_many :requests
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :requests
  belongs_to :department

  def formatted_name
    "#{ firstname } #{ lastname }"  
  end

end

app/controllers/admins/registrations_controller.rb
class Admins::RegistrationsController < Devise::RegistrationsController


private
 
  def sign_up_params
    params.require(:user).permit(:firstname, 
                                 :lastname, 
                                 :department_id, 
                                 :email, 
                                 :password, 
                                 :password_confirmation)
  end
 
  def account_update_params
    params.require(:user).permit(:firstname, 
                                 :lastname, 
                                 :department_id, 
                                 :email, 
                                 :password, 
                                 :password_confirmation, 
                                 :current_password)
  end  
 
end

app/controllers/admins/sessions_controller.rb
class Admins::SessionsController < Devise::SessionsController

  # From Devise for AJAX Authenticate
  def new
    respond_to do |format|
      format.js
      format.html { redirect_to root_path, alert: "Неверное сочетание логина/пароля" }
    end
  end
  
  # Redirect after sign in
  def after_sign_in_path_for(resource_or_scope)
    requests_path(current_user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  
  def new
    @department = Department.new
  end

  def create
    @department = Department.new(department_params)
    if @department.save
      flash[:notice] = "Отдел добавлен"
      redirect_to settings_path
    else
      flash[:error] = "Ошибка"
    end 
  end


private

  def department_params
    params.require(:department).permit(:name, :number_of_employees)
  end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  
  skip_before_action :authenticate_user!, only: [:is_user_login]
  before_action :find_request, except: [:is_user_login, :create, :index, :new ]

  def is_user_login
    if user_signed_in?
      redirect_to requests_path
    else
      render 'is_user_login'
    end
  end

  def edit
  
  end
  
  def show
       
  end
  
  def update
    if @request.update(request_params)
      redirect_to requests_path
    else
      render 'edit'
    end
  end

  def new
    @request = Request.new
  end

  def create
    @request = Request.new(request_params)
    if @request.save
      redirect_to requests_path(current_user)
    else
     render 'new'
    end
  end

  def index
    if params[:my_requests]
      @requests = current_user.requests.all
    else
      @requests = Request.find_requests(params[:search]).order(:id)
    end
  end

  def destroy
    @request.destroy
    redirect_to requests_path
  end

private
  
  def request_params
    params.require(:request).permit(:initiator, 
                                    :responsible, 
                                    :comment, 
                                    :sla_number, 
                                    :time_for_deadline, 
                                    :department_id, 
                                    :user_id, 
                                    :division, 
                                    :status, 
                                    :sla_id)
  end
  
  def find_request
    @request = Request.find(params[:id])
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  
  def new
    @search = Search.new
  end

  def create
    @search = Search.create(search_params)
    redirect_to @search
  end
  
  def show

    # присваиваем только что созданные параметры поиска переменной @search
    @search = Search.find(params[:id])
    
    # присваиваем результат работы метода requests (отбор нужных заявок) переменной @requests
    @requests = @search.requests
    render 'requests/index'
  end

private

  def search_params
    params.require(:search).permit(:keywords, :sla, :deadline, :request_id, :responsible, :division)
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController


  def add_newuser
    render 'devise/registrations/new'
  end
 

end

app/controllers/slas_controller.rb
class SlasController < ApplicationController
  
  def new
    @sla = Sla.new
    @slas = Sla.all
  end
  
  def create
    @sla = Sla.create(sla_params)
    if @sla.save
      redirect_to action: 'new'
    else 
      flash[:notice] = "Не сохранилось"
      redirect_to action: 'new'
    end
  end

  def destroy
    @sla = Sla.find(params[:id])
    @sla.destroy
    redirect_to new_sla_path
  end

private

  def sla_params
    params.require(:sla).permit(:sla_value, :time_for_deadline)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/departments/new.html.erb
<h1>Создать новое подразделение</h1>
<%= simple_form_for :department, html: {class: 'form-horizontal' } do |f| %>
  <%= f.input :name, label: 'Название'  %>
  <%= f.input :number_of_employees, label: 'Количество сотрудников' %>
  <%= f.button :submit, label: 'Создать', class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EasyHD</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= link_to image_tag("logo.png", class: "image_logo"), requests_path  %>
    <div id="logo">
      <ul class="menu-application" style="text-align: right;">
        <li><%= link_to 'Редактировать профиль', edit_user_registration_path, { class: "btn btn-success" } %></li>
        <li><%= link_to 'Выйти', destroy_user_session_path, { class: "btn btn-success", method: :delete }  %> </li>
      </ul>
      <div id="horizontal_menu">
        <ul class="hmenu" style="text-align: right;">
          <li><%= link_to 'Настройки', settings_path %></li>
        </ul>
      </div>
  </div>

    <% if notice || alert %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
</body>
</html>

app/views/requests/_form.html.erb
<% if @request.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@request.errors.count, "error") %> prohibited
    this Request from being saved:</h2>
    <ul>
      <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
     </ul>
  </div>
  </br>
<% end %>
<%= simple_form_for @request,  html: { class: 'form-horizontal', id: "request_form"} do |f| %>
  <%= f.input :status, collection: ["Новая","В работе","Приостановлена", "На подтверждении", "Закрыта"], label: 'Статус'  %>
  <%= f.input :initiator, label: 'Инициатор'  %>
  <%= f.input :department_id, collection: Department.all, value_method: :id, label_method: :name, label: 'Назначить на отдел' %>
  <%= f.input :user_id, collection: Department.all, as: :grouped_select, group_method: :users, group_label_method: :name, label_method: :formatted_name, label: 'Ответственный' %>
  <%= f.input :comment, label: 'Комментарий' %>
  <%= f.input :division, as: :hidden %>
  <%= f.input :sla_number, as: :hidden %>
  <%= f.input :responsible, as: :hidden %>
  <%= f.input :sla_id, collection: Sla.all, value_method: :id, label_method: :sla_value, label: 'SLA' %>
  <%= f.button :submit, label: 'Создать', class: "btn btn-primary" %>
<% end %>

app/views/requests/create.html.erb
<h1>Requests#create</h1>
<p>Find me in app/views/requests/create.html.erb</p>

app/views/requests/edit.html.erb
<h1>Создать обращение</h1>
<%= render 'form' %>

app/views/requests/find.html.erb
<h2>Поиск заявок</h2>
  <%= form_tag find_by_attributes_path, method: "get", class: 'form-horizontal', id: "request_form" do %>
  <%= label_tag :status, "Статус" %>
  <%= select_tag :status, options_for_select([["Новая"],["В работе"], ["Приостановлена"]]) %>
  <%= label_tag :id, "Номер заявки" %>
  <%= text_field_tag :id %>
  <%= label_tag :comment, "Комментарий" %>
  <%= text_field_tag :comment %>
  <%= label_tag :initiator, "Инициатор" %>
  <%= text_field_tag :initiator %>
  <%= label_tag :division, "Отдел" %>
  <%= select_tag :division, options_from_collection_for_select(Department.all, :name, :name) %>
  <%= label_tag :responsible, "Ответственный" %>
  <%= select_tag :responsible, options_from_collection_for_select(User.all, :formatted_name, :formatted_name) %>
  <%= label_tag :status, "SLA" %>
  <%= select_tag :status, options_for_select([[0],[1],[2],[3],[4]]) %><br/>
  <br/>
  <%= submit_tag "Поиск", class: "btn btn-primary" %>
<% end %>

app/views/requests/index.html.erb
<p style="margin: 15px 0 20px 20px; display: inline-block; font-weight: bold; font-size: 16px;">Главная, пользователь: <%= current_user.formatted_name %></p>
<%= form_tag requests_path, method: "get", class: "form_search" do %>
  <%= text_field_tag :search %>
  <%= submit_tag "Поиск", name: nil, class: "btn btn-primary" %>
<% end %>
<hr style="color: #3498db; background-color: #3498db; height: 5px;">
<div id="auth_block"></div>
  <table class="table table-striped">
    <tr>
      <th>Номер</th>
      <th>Статус</th>
      <th>Заявитель</th>
      <th>Комментарий</th>
      <th>Ответственный</th>
      <th>Подразделение</th>
      <th>SLA</th>
      <th>Дата создания</th>
      <th>Срок исполнения</th>
      <th colspan="12"></th>
    <tr>
    <% @requests.each do |request| %>
      <% if request.check_deadline_status %>
        <tr style="color: red">
      <% else %>
        <tr>
      <% end %>
        <td><%= request.id %></td>
        <td><%= request.status %></td>
        <td><%= request.initiator %></td>
        <td><%= request.comment %></td>
        <td><%= request.responsible %></td>
        <td><%= request.division %></td>
        <td><%= request.sla_number %></td>
        <td><%= request.created_at.strftime("%d/%m/%Y") %> </td>
        <td><%= request.deadline.strftime("%d/%m/%Y в %H:%M") %></td>
        <td><%= link_to 'Открыть', edit_request_path(request) %></td>
        <td><%= link_to 'Удалить', request_path(request), method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      </tr>
    <% end %>
  </table>
<ul class = "menu-index" >
  <li><%= link_to "Мои заявки", requests_path(my_requests: true), { class: "btn btn-primary", role: "button" } %></li>
  <li><%= link_to "Создать заявку", new_request_path, { class: "btn btn-primary", role: "button" } %></li>
  <li><%= link_to "Поиск",  new_search_path, { class: "btn btn-primary", role: "button" } %></li>
  <li><%= link_to "Все заявки", requests_path, { class: "btn btn-primary", role: "button" } %></li>
</ul>

app/views/requests/is_user_login.html.erb
<h1>Easy HD</h1>
<p>Система технической поддержки для вашего бизнеса</p>
<div id="auth_block"></div>
<ul class="hmenu">
  <%= render 'devise/menu/registration_items' %>
  <%= render 'devise/menu/login_items' %>
</ul>

app/views/requests/new.html.erb
<h1>Создать обращение</h1>
<%= render 'form' %>

app/views/searches/new.html.erb
<h2>Поиск заявок</h2>
<%= simple_form_for @search, html: {class: 'form-horizontal', id: "request_form"} do |f| %>
  <%= f.input :request_id, label: "Номер заявки" %>
  <%= f.input :keywords, label: "Ключевые слова" %>
  <%= f.input :division, collection: Department.all, value_method: :name, label_method: :name, label: 'Отдел' %>
  <%= f.input :responsible, collection: Department.all, as: :grouped_select, group_method: :users, group_label_method: :name, label_method: :formatted_name, value_method: :formatted_name,  label: 'Ответственный' %>
  <%= f.input :sla, collection: Sla.all, label_method: :sla_value, value_method: :sla_value, label: 'SLA' %>
  <%= f.input :deadline, selected: Date.today - 1.month , start_year: Date.today.year - 5, order: [:day, :month, :year], label: 'Срок исполнения'  %>
  <%= f.button :submit, label: 'Искать', class: "btn btn-primary" %>
 <% end %>

app/views/settings/newuser.html.erb
<h2>Добавить нового пользователя</h2>

<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>

  <div><%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %></div>
  <div><%= f.label :password %> <% if @validatable %><i>(<%= @minimum_password_length %> characters minimum)</i><% end %><br />
    <%= f.password_field :password, autocomplete: "off" %></div>
  <div><%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %></div>
  <div>Отдел<br />
    <%= collection_select :user, :department_id, Department.all, :id, :name  %></div>
  <div><%= f.submit "Создать" %></div>
<% end %>

app/views/settings/show.html.erb
<h1>Настройки</h1>
<ul id = "vertical_menu">
  <li><%= link_to "Создать новое подразделение", new_department_path %></li>
  <li><%= link_to "Создать пользователя", add_newuser_path %></li>
  <li><%= link_to "Настройка SLA", new_sla_path %></li>
</ul>

app/views/slas/new.html.erb
<h1>Создать SLA</h1>
<%= simple_form_for :sla, url: slas_path, html: {class: 'form-horizontal' } do |f| %>
  <%= f.input :sla_value, label: 'Значение'  %>
  <%= f.input :time_for_deadline, label: 'Кол-во часов' %>
  <%= f.button :submit, label: 'Создать', class: "btn btn-primary" %>
<% end %>
<table class="table table-striped">
    <tr>  
      <th>SLA</th>
      <th>Кол-во часов</th>
      <th colspan="3"></th>
    <tr>
    <% @slas.each do |sla| %>
        <td><%= sla.sla_value %></td>
        <td><%= sla.time_for_deadline %></td>
        <td><%= link_to 'Удалить', sla_path(sla), method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      </tr>
    <% end %>
  </table>